### ISSUE TITLE
Not binding to geoclue D-Bus on Ubuntu (Mate) 22.04

### ISSUE THREAD

**Issue by stroobandt** [flathub/app.organicmaps.desktop#19]
Organic Maps runs pretty well on Ubuntu Mate 22.04, except for geolocation.
I have added the following lines to `/etc/geoclue/geoclue.conf` and restarted the `geoclue` service, to no avail:

```
[app.organicmaps]
allowed=true
system=false
users=
```
What am I missing? Firefox geolocation works fine with `geoclue`.

**Comment by biodranik** [comment]
Geoclue (and/or other Linux location services support) should be implemented. https://gitlab.freedesktop.org/geoclue/geoclue/-/wikis/home

**Comment by fgaz** [comment]
Opened https://github.com/organicmaps/organicmaps/issues/3870. I'll leave this open so we remember to add the appropriate dbus permission to the flatpak if organicmaps adds geoclue support.

**Comment by stroobandt** [comment]
This problem may occur when a Qt `desktopID` different from the (flatpak) application name `app.organicmaps.desktop` was defined for communicating with `geoclue` over the D-Bus. See also: https://doc.qt.io/qt-6/position-plugin-geoclue2.html

Any regular GNU/Linux flatpak user is left clueless —pun intended— of what that `desktopId` might be. A consistently defined ID is required for granting Organic Maps permission to use the `geoclue` service in `/etc/geoclue/geoclue.conf`

```
# Application configuration options
#
# NOTE: Having an entry here for an application with allowed=true means that
#       geoclue will not ask agent to authorize the application. This is to
#       ensure that applications with built-in authorization mechanism (e.g web
#       browsers) do not have to be bound to agents.
#
#       If your application is denied access to location information and your
#       operating system doesn't provide any mechanism to change that, it is
#       likely a bug in your operation system (or geoclue). The solution is to
#       report the issue with all details, rather than adding your application
#       to this list.
#
# Format:
#
# # Desktop ID of application without .desktop part

[app.organicmaps.desktop]
allowed=true
system=false
users=
```
To add to the confusion, the Linux desktop flatpak application in `/var/lib/flatpak/app/app.organicmaps.desktop/current/active/files/share/applications`
is called `app.organicmaps.desktop.desktop`, where the first `.desktop` refers to the desktop variant of the application and the second `.desktop` is the file name extension. Hence, what needs to go in `/etc/geoclue/geoclue.conf` has the appearance of not complying with the documentation comments, when in fact, it does.

**Comment by stroobandt** [comment]
Much also depends on whether the particular GNU/Linux desktop environment (DE) in use is implementing a `geoclue`-agent. If it is not, Organic Maps should first launch the `geoclue` demo agent, prior to launching the main program. This is most probably something that must be added to the Linux desktop flatpak by default.

The `geoclue` project is astonishingly poorly documented. I just happen to learn this from this casual [`geoclue` issue comment](https://gitlab.freedesktop.org/geoclue/geoclue/-/issues/143#note_785369).

**Comment by Ferenc-** [comment]
So just for the record, I am running geoclue enabled flatpacked applications (Qt and non-QT as well) on `Ubuntu 22.04`, with the original out of the box geoclue config.
And in this rather reproducible setup, you absolutely do **not** have to touch  `/etc/geoclue/geoclue.conf`,
and I advise everyone to **leave that alone**!
And especially no need to fiddle with `desktopId`.
The only two things that you normally have to do are:
1. Enable `Location Services` in the system settings under `Privacy`.
2. When you first start the geoclue enabled application, which has the flatpak permission to talk to `org.freedesktop.GeoClue2.*`, then a pop-up will appear where you have to confirm once again, that you are OK with providing your location data to the application.

And that is it, I have accuracy level `exact`, GNSS sourced location info latitude longitude super accurate on my laptop, wherever I go. BTW, the GNSS firmware which as of now determines the modem as well is [from the modem distro](https://github.com/the-modem-distro/pinephone_modem_sdk).

Now, the issue with organicmaps on Linux has been andwered by biodranik already. Simply it is a missing feature.
That location button as of now only works with apple's location provider on MacOS and with nothing else,
so no geoclue here:

````cpp
    explicit DesktopLocationService(LocationObserver & observer)
      : LocationService(observer), m_reportFirstEvent(true)
    {
#if defined(OMIM_OS_MAC)
      m_services.push_back(CreateAppleLocationService(*this));
#endif
    }
````
My main question that I was looking to find answers to,
why is that the `AppleLocationService` not implemented in terms of [Qt's plugin for macOS positioning](https://doc.qt.io/qt-5/qtpositioning-plugins.html) , if this classe is only used for desktop anyway?
And wouldn't it make sense to implement the `geoclue` support in terms of the [geoclue2 Qt plugin](https://doc.qt.io/qt-5/qtpositioning-plugins.html)?
Or should we write our own code, interfacing with geoclue2 directly?
Interestingly for example a relatively popular Qt based mapping software in the Linux world simply just copies Qt 5's LGPL3 licenced geoclue2 plugin code.

**Comment by biodranik** [comment]
There were no qt positioning plugins in 2010, when we started the project.

I didn't use them and don't know about license compatibility or min system requirements. Maybe it's easy to reuse. Or maybe it's not hard to implement a raw API.

What is the full picture of all pros and cons?

**Comment by Josh-SMU** [comment]
> So just for the record, I am running geoclue enabled flatpacked applications (Qt and non-QT as well) on `Ubuntu 22.04`, with the original out of the box geoclue config. And in this rather reproducible setup, you absolutely do **not** have to touch `/etc/geoclue/geoclue.conf`, and I advise everyone to **leave that alone**! And especially no need to fiddle with `desktopId`. The only two things that you normally have to do are:
> 
>     1. Enable `Location Services` in the system settings under `Privacy`.
> 
>     2. When you first start the geoclue enabled application, which has the flatpak permission to talk to `org.freedesktop.GeoClue2.*`, then a pop-up will appear where you have to confirm once again, that you are OK with providing your location data to the application.
> 
> 
> And that is it, I have accuracy level `exact`, GNSS sourced location info latitude longitude super accurate on my laptop, wherever I go. BTW, the GNSS firmware which as of now determines the modem as well is [from the modem distro](https://github.com/the-modem-distro/pinephone_modem_sdk).
> 
> Now, the issue with organicmaps on Linux has been andwered by biodranik already. Simply it is a missing feature. That location button as of now only works with apple's location provider on MacOS and with nothing else, so no geoclue here:
> 
> ```c++
>     explicit DesktopLocationService(LocationObserver & observer)
>       : LocationService(observer), m_reportFirstEvent(true)
>     {
> #if defined(OMIM_OS_MAC)
>       m_services.push_back(CreateAppleLocationService(*this));
> #endif
>     }
> ```
> 
> My main question that I was looking to find answers to, why is that the `AppleLocationService` not implemented in terms of [Qt's plugin for macOS positioning](https://doc.qt.io/qt-5/qtpositioning-plugins.html) , if this classe is only used for desktop anyway? And wouldn't it make sense to implement the `geoclue` support in terms of the [geoclue2 Qt plugin](https://doc.qt.io/qt-5/qtpositioning-plugins.html)? Or should we write our own code, interfacing with geoclue2 directly? Interestingly for example a relatively popular Qt based mapping software in the Linux world simply just copies Qt 5's LGPL3 licenced geoclue2 plugin code.

@biodranik It may help to name the unnamed Qt application that is doing this already: Puremaps (https://github.com/rinigus/pure-maps)

**Comment by Ferenc-** [comment]
@stroobandt Please check, this build, I have tested it on `22.04`:
`flatpak install --user https://dl.flathub.org/build-repo/48680/app.organicmaps.desktop.flatpakref`

**Comment by Ferenc-** [comment]
Done in https://github.com/flathub/app.organicmaps.desktop/pull/60

**Comment by tristanvigar** [comment]
Updated to new Organic Maps (Organic Maps 2023.09.22-1-3fc5d2277-dirty-Linux) via Flathub on Librem 5 (PureOS 10/6.3.0-1-librem5) today and Organic Maps crashes after when allowing location access (Location Services is already on via Settings). Launched again using **flatpak run app.organicmaps.desktop** to try to get more information. This is what I saw:

qt.positioning.geoclue2: Unable to start the client: "org.freedesktop.DBus.Error.AccessDenied" "Agent rejected 'app.organicmaps.desktop' for user '1000'. Please ensure that 'app.organicmaps.desktop' has installed a valid app.organicmaps.desktop.desktop file"

Geoclue version: 2.7.0-1pureos1~byz1

Is there anything immediately obvious that I could attempt to troubleshoot with or does this look like a PureOS/Purism issue that I should redirect accordingly? If there is anything I can do to help test, I'm happy to help.

**Comment by Ferenc-** [comment]
@tristanvigar
I think this should go into a separate issue, because it doesn't have much common with the original problem.

> Is there anything immediately obvious that I could attempt to troubleshoot with

Does geoclue work well in other applications?

What is in `/etc/geoclue/geoclue.conf` ?

**Comment by Ferenc-** [comment]
Never mind it is reproducible already.
