### ISSUE TITLE
Add @Ferenc- to Flatpak maintainers?

### ISSUE THREAD

**Issue by fgaz** [flathub/app.organicmaps.desktop#22]
@Ferenc- you've been taking care of updates for a while, I think you should be a flatpak maintainer. Are you and @biodranik ok with that?

**Comment by biodranik** [comment]
@fgaz yes, please ) We're glad for any bits of help. It is overwhelmingly time-consuming to support the project of such a big scale ;-)

**Comment by barthalion** [comment]
Just sent an invite to @Ferenc-.

**Comment by Ferenc-** [comment]
> Just sent an invite to @Ferenc-.

Many thanks @barthalion, I have accepted. I think this can be closed now.
