### ISSUE TITLE
Should be clear about alpha state, update screenshots to reflect actual package

### ISSUE THREAD

**Issue by endim8** [flathub/app.organicmaps.desktop#26]
at the moment, OM Desktop's state isn't really conveyed properly, and the screenshots aren't actually of the desktop app. it'd be good to clearly specify that this is alpha and not meant for end-users
![Screenshot from 2023-02-03 22-14-17](https://user-images.githubusercontent.com/26939824/216721284-afeb4371-0d69-46a1-9ff2-693d77e0e9b9.png)

**Comment by biodranik** [comment]
CC @Ferenc-

**Comment by Ferenc-** [comment]
Is there somewhere an organized list of issues (perhaps a GH milestone?), so that it is known why exactly is the alpha state, or in other words what is needed for the next level?
Regarding screenshots, is there even an agreement on what should be achieved ideally? Is there a HIG to follow?
Should the QT UI be made more or less convergent with Qt Quick, and perhaps some extra frameworks on top of that?
And then where to stop? At least in theory QT UIs could be deployable on the rest of the platforms as well, which is not the current way thing go.

**Comment by biodranik** [comment]
Android and iOS UI will stay native for performance and complexity reasons.

I'm not sure that Qt Quick is a good idea. Will performance degrade after switching to it? Will mobile devices become less responsive or consume more battery when using Qt Quick? Will it increase the complexity of the code support?

**Comment by bam80** [comment]
Hello,
I don't share your concerns - Qt Quick was designed for mobile devices in the first place, and QML can be pre-compiled these days, AFAIK.
IMO, Qt Quick or possibly Kirigami should be a good candidates for the UI framework.
I'm not involved in this project though (yet?), so sorry for my bravery.

**Comment by fgaz** [comment]
I think that should be discussed upstream, this is the issue tracker for the flathub package.

Anyway, if anyone is willing to share some good screenshots under CC0-1.0, I (or anyone else) could submit them [upstream](https://github.com/organicmaps/organicmaps/blob/0fbe6952d4400d8a1f5b4c2b688630123d0bcd57/packaging/app.organicmaps.desktop.metainfo.xml#L97-L107).

**Comment by bam80** [comment]
Right, sorry.
I've created a discussion upstream:
https://github.com/organicmaps/organicmaps/discussions/4408

**Comment by biodranik** [comment]
@bam80 Do you think that JavaScript VM will beat C++ rendering speed? OM is popular now mainly to its simplicity _and rendering speed_.

> JavaScript Code
  Most QML applications will have a large amount of JavaScript code in them, in the form of dynamic functions, signal handlers, and property binding expressions. This is generally not a problem. Thanks to some optimizations in the QML engine, such as those done to the bindings compiler, it can (in some use-cases) be faster than calling a C++ function. However, care must be taken to ensure that unnecessary processing isn't triggered accidentally.

**Comment by bam80** [comment]
As suggested, let's please keep the discussion upstream. ^
About the rendering speed, I think there should be no concerns in this case, as map itself is rendered natively anyway.

**Comment by Ferenc-** [comment]
@endim8 The [changes are visible on flathub](https://flathub.org/apps/details/app.organicmaps.desktop). Please confirm if this can be closed.

**Comment by endim8** [comment]
LGTM! thank you :)

**Comment by RokeJulianLockhart** [comment]
> https://github.com/flathub/app.organicmaps.desktop/issues/26#issuecomment-1430253874

@Ferenc-, "Routing in light mode" and "Routing in dark mode" are switched:

1. ![Screenshot_20250105_181340](https://github.com/user-attachments/assets/0af637d1-0f98-420b-a2d7-9ca0f415467c)
1. ![Screenshot_20250105_181346](https://github.com/user-attachments/assets/1bf72b66-b398-4a53-8c8d-56561491e408)
