### ISSUE TITLE
please make use of flathub-beta channel for test builds

### ISSUE THREAD

**Issue by bam80** [flathub/app.organicmaps.desktop#34]
Could we please make an unofficial test build from master, to test recent Qt6 port?
For that, [flathub-beta](https://discourse.flathub.org/t/how-to-use-flathub-beta/2111) repository exists.
Could we make use of it?

> The way this works is that each GitHub repository builds the master branch for the stable repository, which will have the flatpak branch name “stable”, and then the beta git branch will build into the beta repository with the flatpak branch “beta”.

https://blogs.gnome.org/alexl/2019/02/19/changes-in-flathub-land/

So essentially we need to create "beta" branch here which points to master or some commit there.

@Ferenc-

**Comment by bam80** [comment]
If help is needed, please let me know

**Comment by biodranik** [comment]
That sounds good to me to test some breaking changes. Can beta be automated and always published from the latest master branch?

**Comment by bam80** [comment]
To do that, we would need to request an exception as here, otherwise Flathub will always require tag/commit:
https://github.com/hadess/flatpak-builder-lint/commit/3674e0d37f8344567f0c146a2863e473aed912cb

**Comment by Ferenc-** [comment]
The beta channel is usable nowadays.
