### ISSUE TITLE
commits in PR can't be squashed

### ISSUE THREAD

**Issue by bam80** [flathub/app.organicmaps.desktop#42]
Could we enable the feature for this repo?
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/configuring-commit-squashing-for-pull-requests

Also, if possible, we would like to have access to remove the branches, as the `beta` branch is polluted with unsquashed commits now and we created temporary `beta2` to address this which will be unneeded then.

@barthalion @hfiguiere

**Comment by bam80** [comment]
Could you please delete it then, if we can't?

**Comment by barthalion** [comment]
Just did.

**Comment by bam80** [comment]
@barthalion Thanks you.
As we can't check the squashing right now, I'm closing this, in case of future problems I'll return to you :+1:
