### ISSUE TITLE
Qt6: OpenGL Desktop context is requested on mobile Linux instead of ES one

### ISSUE THREAD

**Issue by bam80** [flathub/app.organicmaps.desktop#50]
This revealed #36 but probably a problem per se.
Note Qt5 seem correctly сhooses ES context on PP and GL one on Desktop.

Possible reasons might be:
our Qt6 port, changes in Qt6 code or the way the library is configured in Flatpak Runtime:
https://github.com/flathub/app.organicmaps.desktop/blob/236b8a4cfe5cfeca6c0a7e53c6a72433a97b70c7/app.organicmaps.desktop.yml#L2-L3

**Comment by Ferenc-** [comment]
According to @biodranik the observed behavior on the PP OG with [Qt 6 is the correct one](https://github.com/flathub/app.organicmaps.desktop/issues/36#issuecomment-1623599403).
And we already have [a working solution for that (PP OG on Qt 6)](https://github.com/organicmaps/organicmaps/pull/5484#discussion_r1257501413).
If and when there is actual evidence for an incorrect behavior, then we should re-open this.

**Comment by biodranik** [comment]
@Ferenc- did you see any performance/rendering speed slowdown with Qt6?

**Comment by Ferenc-** [comment]
> @Ferenc- did you see any performance/rendering speed slowdown with Qt6?

So far I have not observed any with Qt 6.

**Comment by biodranik** [comment]
Let's start with checking if qt6 was built with GLES2.0 support for PinePhone

**Comment by bam80** [comment]
I checked my local Qt6 build and without any special configuration options it seems GLES is not supported:
```
  OpenGL:
    Desktop OpenGL ....................... yes
    OpenGL ES 2.0 ........................ no
    OpenGL ES 3.0 ........................ no
    OpenGL ES 3.1 ........................ no
    OpenGL ES 3.2 ........................ no
  Vulkan ................................. yes
```

Qt5 Runtime has the option needed (`-opengl es2`):
```
$ flatpak run org.kde.Platform
Similar installed refs found for ‘org.kde.Platform’:

   1) runtime/org.kde.Platform/x86_64/5.15 (user)
   2) runtime/org.kde.Platform/x86_64/5.15-22.08 (user)
   3) runtime/org.kde.Platform/x86_64/6.5 (user)
   4) runtime/org.kde.Platform/x86_64/5.15-22.08 (system)

Which do you want to use (0 to abort)? [0-4]: 1
[📦 org.kde.Platform ~]$ cat /usr/manifest.json
...
      "build-options" : {
        "arch" : {
          "aarch64" : {
            "config-opts" : [
              "-no-reduce-relocations",
              "-optimize-size",
              "-opengl es2"
            ]
          },
          "x86_64" : {
            "config-opts" : [
              "-reduce-relocations",
              "-force-debug-info"
            ]
          }
        }
...
```
But I don't see it in the same place of Qt6 build:
```
      ],
      "build-options" : {
        "arch" : {
          "aarch64" : {
            "config-opts" : [
              "-DINSTALL_LIBDIR=/usr/lib/aarch64-linux-gnu"
            ]
          },
          "x86_64" : {
            "config-opts" : [
              "-DINSTALL_LIBDIR=/usr/lib/x86_64-linux-gnu"
            ]
          }
        }
```

So the problem might very well be related with the build indeed.

Let's please reopen this issue and I'll reference it doing patch upstream.

**Comment by bam80** [comment]
OpenGL configure options used for KDE runtimes:
- runtime/org.kde.Platform/aarch64/5.15:
```
  OpenGL:
    Desktop OpenGL ....................... no
    OpenGL ES 2.0 ........................ yes
    OpenGL ES 3.0 ........................ yes
    OpenGL ES 3.1 ........................ yes
    OpenGL ES 3.2 ........................ yes
  Vulkan ................................. yes
```
- runtime/org.kde.Platform/aarch64/6.5:
```
  OpenGL:
    Desktop OpenGL ....................... yes
    OpenGL ES 2.0 ........................ no
    OpenGL ES 3.0 ........................ no
    OpenGL ES 3.1 ........................ no
    OpenGL ES 3.2 ........................ no
  Vulkan ................................. yes
```

**Comment by Ferenc-** [comment]
This only means that there is no direct dependency on `OpenGL ES`, which we don't need anyway,
because `-opengl dynamic` [is the default in qt 6, if nothing is provided](https://doc.qt.io/qt-6/windows-graphics.html#dynamically-loading-opengl), which is just fine.
I have tested the `6.5 `flatpak runtime with a simple example,
and if explicitly set `format.setRenderableType(QSurfaceFormat.OpenGLES)`,
then `context.isOpenGLES()` returned `True` for me.

**Comment by bam80** [comment]
@Ferenc- can you provide your example, do you call context.isOpenGLES() _after_ the context is created?

**Comment by Ferenc-** [comment]
> do you call context.isOpenGLES() after the context is created?

Yes.

> can you provide your example

Yes, see below, but from now on, please provide evidence of incorrect behavior...

````python3
#!/usr/bin/env python3
import sys
from PySide6.QtCore import Qt, QSize
from PySide6.QtGui import QOpenGLContext, QSurfaceFormat
from PySide6.QtWidgets import QApplication, QMainWindow, QWidget, QVBoxLayout
from PySide6.QtOpenGLWidgets import QOpenGLWidget


class GLWidget(QOpenGLWidget):
    def __init__(self, parent=None):
        super().__init__(parent)

    def initializeGL(self):
        gl_version_major, gl_version_minor = QSurfaceFormat.defaultFormat().version()
        print(f"OpenGL version: {gl_version_major}.{gl_version_minor}\nIs OpenGLES: {self.context().isOpenGLES()}")

    def paintGL(self):
        # OpenGL rendering code goes here
        pass

    def resizeGL(self, width, height):
        pass


class MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()

        widget = QWidget(self)
        layout = QVBoxLayout()
        widget.setLayout(layout)

        gl_widget = GLWidget(widget)
        layout.addWidget(gl_widget)

        self.setCentralWidget(widget)
        self.setWindowTitle("OpenGL ES 3.0 Context")


if __name__ == "__main__":
    app = QApplication(sys.argv)

    # Request OpenGL ES 3.0 context
    format = QSurfaceFormat()
    format.setRenderableType(QSurfaceFormat.OpenGLES)
    format.setVersion(3, 0)
    format.setProfile(QSurfaceFormat.CoreProfile)
    QSurfaceFormat.setDefaultFormat(format)

    main_window = MainWindow()
    main_window.show()

    sys.exit(app.exec())
````

**Comment by bam80** [comment]
@Ferenc- meanwhile, could you reopen this please?
I will do research yet, and we still didn't solve https://github.com/organicmaps/organicmaps/issues/5391 which might be related.
We can close the issue when we have common understanding of the situation. Thanks.

**Comment by bam80** [comment]
@Ferenc- how did you run your example?
```
$ flatpak run org.kde.Platform
Similar installed refs found for ‘org.kde.Platform’:

   1) runtime/org.kde.Platform/x86_64/5.15 (user)
   2) runtime/org.kde.Platform/x86_64/5.15-22.08 (user)
   3) runtime/org.kde.Platform/x86_64/6.5 (user)
   4) runtime/org.kde.Platform/x86_64/5.15-22.08 (system)

Which do you want to use (0 to abort)? [0-4]: 3
[📦 org.kde.Platform ~]$ 

# in other terminal
$ flatpak enter 3849291639  python3 < ./egl_test
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
ModuleNotFoundError: No module named 'PySide6'

**Comment by biodranik** [comment]
Should qt6 for PinePhone have gles 2.0 enabled?

**Comment by bam80** [comment]
> OpenGL ES is a flavor of the OpenGL specification intended for embedded devices. 

So as I see the situation, we can expect more stable and error-prone drivers support from GLES on mobile. It also can be more suitable for embedded underpowered devices.
I can't even see if OGL Desktop is required or somehow mentioned in any Android version:
https://developer.android.com/develop/ui/views/graphics/opengl/about-opengl#choosing-version

For Desktop, it should be indifferent as soon as we don't use GL Desktop API in our rendering engine anyway.

So it should be perfectly safe to just rely on ES unconditionally and enforce it whenever possible.
Sure, our code should still work if no ES context is available. But I expect it might be provided automatically, without any additional efforts. Should be still checked.

**Comment by bam80** [comment]
> Should qt6 for PinePhone have gles 2.0 enabled?

If I understand the sample from @Ferenc- above right (still there is a question with the context creation but I'll skip it for now) - both OGL and GLES are actually enabled it Qt6, it's just a matter of what is used by default.
Still it doesn't quite corresponds with what we see in the configuration logs..

This question still needs to be evaluated.

**Comment by bam80** [comment]
> I have tested the 6.5 flatpak runtime with a simple example,
and if explicitly set format.setRenderableType(QSurfaceFormat.OpenGLES),
then context.isOpenGLES() returned True for me.

@Ferenc- I tried to do [the same](https://github.com/organicmaps/organicmaps/pull/5526) in our code and failed - we can see the same OGL 2.0 (not ES) is still resulted after the context create:
```
$ flatpak run --env=MESA_GLSL_VERSION_OVERRIDE=150 --env=MESA_GL_VERSION_OVERRIDE=2.0  app.organicmaps.desktop//test
LOG TID(1) INFO   2.3043e-05 qt/main.cpp:121 main(): Organic Maps 2023.07.12-1-324ab8c6-dirty-Linux started, detected CPU cores: 4
...
LOG TID(1) INFO      3.68194 qt_common/map_widget.cpp:362 initializeGL(): Vendor: Intel 
Renderer: Mesa Intel(R) HD Graphics 4400 (HSW GT2) 
Version: 2.0 Mesa 23.1.1 (git-fa55e3c026) 
Shading language version:
 1.50 
...
LOG TID(1) INFO      3.68202 qt_common/map_widget.cpp:386 initializeGL(): Contex is LibGL, try to override..
LOG TID(1) INFO      3.68204 qt_common/map_widget.cpp:390 initializeGL(): OpenGL version is below 3.2, taking the OpenGL 2.1 path
LOG TID(1) INFO      3.68268 drape_frontend/visual_params.cpp:58 Init(): Visual scale = 1 ; Tile size = 1024
LOG TID(3) INFO      3.68289 drape_frontend/backend_renderer.cpp:724 Do(): Start routine.
LOG TID(3) INFO      3.68291 drape_frontend/backend_renderer.cpp:692 OnContextCreate(): On context create.
LOG TID(4) INFO      3.68331 drape_frontend/frontend_renderer.cpp:2414 Do(): Start routine.
LOG TID(4) INFO      3.68333 drape_frontend/frontend_renderer.cpp:2331 OnContextCreate(): On context create.
LOG TID(3) INFO      3.76705 drape/support_manager.cpp:35 Init(): Renderer = Mesa Intel(R) HD Graphics 4400 (HSW GT2) | Api = OpenGLES2 | Version = 2.0 Mesa 23.1.1 (git-fa55e3c026)
```

So either your sample is incorrect and the Qt6 build does NOT actually have ES support or I'm doing something wrong.

**Comment by Ferenc-** [comment]
Your enforcement attempt comes too late in the initialization procedure and has no effect.
Please try this patch on top of organicmaps `master`:
````diff
diff --git a/qt/qt_common/helpers.cpp b/qt/qt_common/helpers.cpp
index a977fe4864..fb28f80a7a 100644
--- a/qt/qt_common/helpers.cpp
+++ b/qt/qt_common/helpers.cpp
@@ -53,6 +53,7 @@ void SetDefaultSurfaceFormat(QString const & platformName)
   fmt.setSwapBehavior(QSurfaceFormat::DoubleBuffer);
   fmt.setSwapInterval(1);
   fmt.setDepthBufferSize(16);
+  fmt.setRenderableType(QSurfaceFormat::OpenGLES);
 
   // Set proper OGL version now (needed for "cocoa" or "xcb"), but have troubles with "wayland" devices.
   // It will be resolved later in MapWidget::initializeGL when OGL context is available.

````
And then you should see this in the logs:
````
LOG TID(1) INFO     0.961323 qt_common/map_widget.cpp:362 initializeGL(): Vendor: Intel 
Renderer: Mesa Intel(R) HD Graphics 4600 (HSW GT2) 
Version: OpenGL ES 3.2 Mesa 23.1.1 (git-fa55e3c026) 
Shading language version:
 OpenGL ES GLSL ES 3.20 
 [...]
LOG TID(1) INFO     0.961408 qt_common/map_widget.cpp:370 initializeGL(): Context is LibGLES
LOG TID(1) DEBUG    0.961477 qt_common/map_widget.cpp:378 initializeGL(): Found OpenGL ES 2.0 extension:  GL_EXT_map_buffer_range
LOG TID(1) DEBUG      0.9615 qt_common/map_widget.cpp:378 initializeGL(): Found OpenGL ES 2.0 extension:  GL_OES_mapbuffer
LOG TID(1) DEBUG    0.961519 qt_common/map_widget.cpp:378 initializeGL(): Found OpenGL ES 2.0 extension:  GL_OES_vertex_array_object

````

**Comment by bam80** [comment]
@Ferenc- thanks, I realized it already.
We have suspect this won't work on Mac OS, though.

Existing format manipulations in `initializeGL()` apparently do not have effect, too. That all looks quite buggy to me..

**Comment by Ferenc-** [comment]
> We have suspect this won't work on Mac OS, though

First of all, that alone would not be a big issue. We could put this setting behind the usual macro:
`````cpp
#if defined(OMIM_OS_LINUX)
  fmt.setRenderableType(QSurfaceFormat::OpenGLES);
#endif
````` 
And then Mac OS wouldn't be impacted....
  
Furthermore, Apple has already abandoned OpenGL, which means that sooner or later non of the current OpenGL code will work on Mac OS anyway.
In order to make the project long term viable on Mac OS,
one has to either rely on `metal` directly, or use `vulkan` over `moltenvk`.
I think last time `meetal` was discussed [here](https://github.com/organicmaps/organicmaps/pull/2947#discussion_r1254637796).

My point is that as long as we have not eliminated the `m_apiOpenGLES3` mess (and it's consequential dependance on GLSL version, that only comes with desktop OpenGL) we should probably not add insult to injury by adding more code, which tries to enforce `OpenGLES`.

**Comment by bam80** [comment]
>  one has to either rely on metal directly, or use vulkan over moltenvk.

or use ANGLE which translates OpenGL ES 2.0/3.0 to Metal:
https://chromium.googlesource.com/angle/angle

**Comment by biodranik** [comment]
To clarify: metal is already used on iOS. And we just need to refactor ifdefs and other deps logic to switch and use metal on Mac OS X too.
But as we are using Mac as our main dev and testing platform, we need to also test androids that use OpenGL and Vulkan (depending on version), and Linux where OpengL is still the only reliable option available.

So in the ideal world we should be able to easily switch from OpenGL to Metal on Macs, and maybe even to Vulkan to test how renderer will work for Android.

**Comment by biodranik** [comment]
Note: Our minimum supported iOS 12 already works with Metal, so OpenGL code can be completely dropped for iOS if necessary.

**Comment by Ferenc-** [comment]
Done in https://github.com/flathub/app.organicmaps.desktop/pull/60
