### ISSUE TITLE
org.kde.Platform branch 6.6 is end-of-life (+ org.freedesktop.Platform.GL.default branch 22.08 etc.)

### ISSUE THREAD

**Issue by alok1111** [flathub/app.organicmaps.desktop#83]
`flatpak update` command shows the following warning:
```
Info: runtime org.kde.Platform branch 6.6 is end-of-life, with reason:
   We strongly recommend moving to the latest stable version of the Platform and SDK
Info: applications using this runtime:
   app.organicmaps.desktop
```

**Comment by Ferenc-** [comment]
As mentioned in https://github.com/flathub/app.organicmaps.desktop/pull/81#issuecomment-2433244995 , I am well aware of this, unfortunately https://github.com/organicmaps/organicmaps/issues/7838 has to be solved first.
