### ISSUE TITLE
org.freedesktop.Platform.GL.default branch 22.08 is end-of-life

### ISSUE THREAD

**Issue by BMiZEL** [flathub/app.organicmaps.desktop#86]
Hi there, f.y.i.

"Info: (pinned) runtime org.freedesktop.Platform.GL.default branch 22.08 is end-of-life, with reason:
   org.freedesktop.Platform 22.08 is no longer receiving fixes and security updates. Please update to a supported runtime version."

**Comment by Ferenc-** [comment]
This is a dependency of `org.kde.Platform branch 6.6`  so in essence this is a duplicate of https://github.com/flathub/app.organicmaps.desktop/issues/83
