### ISSUE TITLE
Remove rsync

### ISSUE THREAD

**Issue by fgaz** [flathub/app.organicmaps.desktop#9]
After https://github.com/organicmaps/organicmaps/pull/2730 is released, rsync won't be needed anymore

(from https://github.com/flathub/app.organicmaps.desktop/pull/8#discussion_r895977515 )

**Comment by Ferenc-** [comment]
Hi @biodranik,
As #12 has been merged and `app.organicmaps.desktop 2022.07.01-6 stable` works well, I think this should be closed.
